#!/bin/bash
# Copyright 2015, Aleph Objects, Inc.
# GPLv3
#
# This script will process a dotfile a few different ways, make a few pngs,
# and display them.
#
# Usage:
# AO-dot-aonet [dotfile]
# Example:
# AO-dot-aonet aonet.dot
#
# Some dot docs:
# http://www.graphviz.org/pdf/dotguide.pdf
# Colors:
# http://www.graphviz.org/doc/info/colors.html
# Neato:
# http://graphviz.org/Documentation/neatoguide.pdf
#
# Run these to generate dot code based on the clusterssh nodes.
# for i in `grep aoworkstations ~/.clusterssh/clusters |head -1` ; do echo -e '\t"LAN" -- {"'$i'"};' ; done >> aonet.dot
# for i in `grep aosqueeze ~/.clusterssh/clusters |head -1` ; do echo -e '\t"Elastichosts " -- {"'$i'"};' ; done  >> aonet.dot
# for i in `grep aowheezy ~/.clusterssh/clusters |head -1` ; do echo -e '\t"Elastichosts " -- {"'$i'"};' ; done  >> aonet.dot
# for i in `grep aojessie ~/.clusterssh/clusters |head -1` ; do echo -e '\t"Elastichosts " -- {"'$i'"};' ; done  >> aonet.dot
# for i in `grep aolaptops ~/.clusterssh/clusters |head -1` ; do echo -e '\t"Internet" -- {"'$i'"};' ; done  >> aonet.dot
# for i in `grep ^bbb- ~/.clusterssh/clusters | cut -f 2- -d " " | sed -e 's/aleph@//g'` ; do echo -e '\t"Cluster" -- {"'$i'"};' ; done  >> aonet.dot

DOTFILE="$@"

neato -Gsplines=true -Goverlap=false -o tmp.png -Tpng "$DOTFILE"
#dot -Goverlap=scale -Gsplines=true -o tmp.png -Tpng "$DOTFILE"
#sfdp -Goverlap=scale -Gsplines=true -o tmp.png -Tpng "$DOTFILE"
#circo -Goverlap=scale -Gsplines=true -o tmp.png -Tpng "$DOTFILE"

